org.gradle.jvmargs=-Xmx768M -Dkotlin.daemon.jvm.options="-Xmx768M" -XX:MaxMetaspaceSize=512m -Djava.net.preferIPv4Stack=true
android.useAndroidX=true
android.enableJetifier=false
org.gradle.parallel=false
org.gradle.daemon=false
kotlin.incremental=false
android.builtInKotlin=false
android.newDsl=false
systemProp.java.net.preferIPv4Stack=true