// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP17NdNPmu29Wo174Kr93gEOouMFpgXvg',
    appId: '1:97136798155:web:d0cf045ca60f0da6526e4e',
    messagingSenderId: '97136798155',
    projectId: 'wankaner-go',
    authDomain: 'wankaner-go.firebaseapp.com',
    storageBucket: 'wankaner-go.firebasestorage.app',
    measurementId: 'G-1R5K4DE5FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3LYsdqiuOf5pquoSDM2psCLEJi3a6I_8',
    appId: '1:97136798155:android:009bb7ac46449823526e4e',
    messagingSenderId: '97136798155',
    projectId: 'wankaner-go',
    storageBucket: 'wankaner-go.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFbvIHgm4fiIoS9VfrahgyaTmORpJDrQM',
    appId: '1:97136798155:ios:62eb9582e1673907526e4e',
    messagingSenderId: '97136798155',
    projectId: 'wankaner-go',
    storageBucket: 'wankaner-go.firebasestorage.app',
    iosBundleId: 'com.example.wankanerGo',
  );
}
